import { Character } from './models';

export const tekkenRoster: Character[] = [
  { name: 'Alisa', image: 'images/alisa.png' },
  { name: 'Anna', image: 'images/anna.png' },
  { name: 'Armor King', image: 'images/Armorking.png' },
  { name: 'Asuka', image: 'images/asuka.png' },
  { name: 'Azucena', image: 'images/azucena.png' },
  { name: 'Bryan', image: 'images/Bryan.png' },
  { name: 'Claudio', image: 'images/claudio.png' },
  { name: 'Clive', image: 'images/clive.png' },
  { name: 'Devil Jin', image: 'images/deviljin.png' },
  { name: 'Dragunov', image: 'images/dragunov.png' },
  { name: 'Eddy', image: 'images/eddy.png' },
  { name: 'Fahkumram', image: 'images/fahkumram.png' },
  { name: 'Feng', image: 'images/feng.png' },
  { name: 'Heihachi', image: 'images/heihachi.png' },
  { name: 'Hwoarang', image: 'images/hwoarang.png' },
  { name: 'Jack-8', image: 'images/jack8.png' },
  { name: 'Jin', image: 'images/Jin.png' },
  { name: 'Jun', image: 'images/jun.png' },
  { name: 'Kazuya', image: 'images/Kazuya.png' },
  { name: 'King', image: 'images/king.png' },
  { name: 'Kuma', image: 'images/Kuna.png' },
  { name: 'Lars', image: 'images/Lars.png' },
  { name: 'Law', image: 'images/law.png' },
  { name: 'Lee', image: 'images/lee.png' },
  { name: 'Leo', image: 'images/leo.png' },
  { name: 'Leroy', image: 'images/leroy.png' },
  { name: 'Lidia', image: 'images/Lidia.png' },
  { name: 'Lili', image: 'images/lili.png' },
  { name: 'Miary', image: 'images/miary.png' },
  { name: 'Nina', image: 'images/nina.png' },
  { name: 'Panda', image: 'images/panda.png' },
  { name: 'Paul', image: 'images/paul.png' },
  { name: 'Raven', image: 'images/raven.png' },
  { name: 'Reina', image: 'images/reina.png' },
  { name: 'Shaheen', image: 'images/shaheen.png' },
  { name: 'Steve', image: 'images/steve.png' },
  { name: 'Victor', image: 'images/victor.png' },
  { name: 'Xiaoyu', image: 'images/xiaoyu.png' },
  { name: 'Yoshimitsu', image: 'images/yoshimitsu.png' },
  { name: 'Zafina', image: 'images/zafina.png' }
];

export const mk11Roster: Character[] = [
  { name: 'Scorpion', image: 'images/scorpion.png' },
  { name: 'Sub-Zero', image: 'images/sub-zero.png' },
  { name: 'Raiden', image: 'images/raiden.png' },
  { name: 'Shao Kahn', image: 'images/shao_kahn.png' },
  { name: 'Liu Kang', image: 'images/liu_kang.png' },
  { name: 'Kitana', image: 'images/kitana.png' },
  { name: 'Kung Lao', image: 'images/kung_lao.png' },
  { name: 'Jax Briggs', image: 'images/jax.png' },
  { name: 'Sonya Blade', image: 'images/sonya.png' },
  { name: 'Johnny Cage', image: 'images/johnny_cage.png' },
  { name: 'Cassie Cage', image: 'images/cassie.png' },
  { name: 'Jacqui Briggs', image: 'images/jacqui.png' },
  { name: 'Geras', image: 'images/geras.png' },
  { name: 'Cetrion', image: 'images/cetrion.png' },
  { name: 'Kollector', image: 'images/kollector.png' },
  { name: "D'Vorah", image: 'images/dvorah.png' },
  { name: 'Kotal Kahn', image: 'images/kotal.png' },
  { name: 'Erron Black', image: 'images/erron_black.png' },
  { name: 'Kabal', image: 'images/kabal.png' },
  { name: 'Kano', image: 'images/kano.png' },
  { name: 'Jade', image: 'images/jade.png' },
  { name: 'Skarlet', image: 'images/skarlet.png' },
  { name: 'Baraka', image: 'images/baraka.png' },
  { name: 'Noob Saibot', image: 'images/noob.png' },
  { name: 'Frost', image: 'images/frost.png' },
  { name: 'Shang Tsung', image: 'images/shang_tsung.png' },
  { name: 'Nightwolf', image: 'images/nightwolf.png' },
  { name: 'Terminator', image: 'images/terminator.png' },
  { name: 'Sindel', image: 'images/sindel.png' },
  { name: 'Joker', image: 'images/joker.png' },
  { name: 'Spawn', image: 'images/spawn.png' },
  { name: 'Fujin', image: 'images/fujin.png' },
  { name: 'Sheeva', image: 'images/sheeva.png' },
  { name: 'RoboCop', image: 'images/robocop.png' },
  { name: 'Mileena', image: 'images/mileena.png' },
  { name: 'Rain', image: 'images/rain.png' },
  { name: 'Rambo', image: 'images/rambo.png' }
];

export const gh3Roster: Character[] = [
  { name: 'Johnny Napalm', image: 'images/johnny_napalm.png' },
  { name: 'Judy Nails', image: 'images/judy_nails.png' },
  { name: 'Axel Steel', image: 'images/axel_steel.png' },
  { name: 'Izzy Sparks', image: 'images/izzy_sparks.png' },
  { name: 'Midori', image: 'images/midori.png' },
  { name: 'Xavier Stone', image: 'images/xavier_stone.png' },
  { name: 'Casey Lynch', image: 'images/casey_lynch.png' },
  { name: 'Lars Umlaut', image: 'images/lars_umlaut.png' },
  { name: 'Tom Morello', image: 'images/tom_morello.png' },
  { name: 'Slash', image: 'images/slash.png' },
  { name: 'Lou', image: 'images/lou.png' },
  { name: 'God of Rock', image: 'images/god_of_rock.png' },
  { name: 'Grim Ripper', image: 'images/grim_ripper.png' }
];
